<?xml version="1.0"?>
<!DOCTYPE Options  [
  <!ELEMENT Options (mobileOptions,terminalProfile,icons,events,spy,boot,bip+)>
  <!ELEMENT mobileOptions (optionsItems)>
  <!ELEMENT optionsItems (terminalInterface,delayDisplay,delayUserResponse,defaultTimeIntervalStatusCommand,statusCommandAvailable,toneDuration,toneType,sizeScreenPolicy,styleScreenPolicy,colorScreenPolicy,cardTimeout,batteryInfo,netsearchmode,IMEI,IMEISV,MEID,cardReset)>
  <!ELEMENT terminalInterface (selectedTerminalInterface,othersTerminaleInterface*)>
  <!ELEMENT selectedTerminalInterface (#PCDATA)>
  <!ELEMENT othersTerminaleInterface (#PCDATA)>
  <!ELEMENT delayDisplay (#PCDATA)>
  <!ELEMENT delayUserResponse (#PCDATA)>
  <!ELEMENT defaultTimeIntervalStatusCommand (#PCDATA)>
  <!ELEMENT statusCommandAvailable (#PCDATA)>
  <!ELEMENT toneDuration (#PCDATA)>
  <!ELEMENT toneType (mute,pc,set1,set2)>
  <!ELEMENT mute (#PCDATA)>
  <!ELEMENT pc (#PCDATA)>
  <!ELEMENT set1 (#PCDATA)>
  <!ELEMENT set2 (#PCDATA)>
  <!ELEMENT sizeScreenPolicy (#PCDATA)>
  <!ELEMENT styleScreenPolicy (#PCDATA)>
  <!ELEMENT colorScreenPolicy (#PCDATA)>
  <!ELEMENT cardTimeout (#PCDATA)>
  <!ELEMENT batteryInfo (#PCDATA)>
  <!ELEMENT netsearchmode (#PCDATA)>
  <!ELEMENT IMEI (#PCDATA)>
  <!ELEMENT IMEISV (#PCDATA)>
  <!ELEMENT MEID (#PCDATA)>
  <!ELEMENT cardReset (#PCDATA)>
  <!ELEMENT terminalProfile (proactiveCommands,downloadProfile,others)>
  <!ELEMENT proactiveCommands (maximumNumberSoftKeys,numberDisplayCharactersDown,numberChannels,bipFilterRetransData,bipLogReceptionData,bipOcpUrl,bipLoadUrl,maxWaitForReceiveData,maxWaitForHttpResponse,numberDisplayCharactersAccross,menuWidthReduction,eventDownloadBrowserTermination,eventDownloadDataAvailable,eventDownloadChannelStatus,eventAccessTechnoChange,eventDisplayParamsChanged,eventLocalConnection,getReaderStatusCardReaderId,launchBrowser,provideLocalInfoAccessTechno,getChannelStatus,serviceSearch,getServiceInfo,declareService,sendData,receiveData,closeChannel,openChannel,GPRS,CSD,bluetooth,IrDA,RS232,screenSizing,variableSizeFonts,textScrolling,textAttributes,textWrapping,displayResizable,UDP,TCPClient,TCPServer,selectItemSoftKey,setupMenuSoftKey,refresh,moreTime,pollInterval,pollingOff,setupCall,sendSs,sendShortMsg,sendUssd,playTone,displayText,getInkey,getInput,selectItem,setupMenu,performCardApdu,powerOnCard,powerOffCard,getReaderStatus,localInfoMcc,localInfoNmr,localInfoLanguage,localInfoTiming,timerManagementStart,timerManagementCurrentValue,localInfoDate,setUpIdleMode,runAtCommand,languageNotification,sendDtmfCommand,timerExpirationStk,eventDownloadCallConnectedStk,eventDownloadCallDisconnectedStk,eventDownloadLocationStatusStk,setUpEventListStk,eventDownloadMTCallStk,userActivityStk,eventDownloadIdleScreenStk,eventDownloadCardReaderStatusStk,eventDownloadLanguageSelectionStk,variableTimeoutDisplayText,helpSupportedGetInkey,USB,variableTimeoutGetInkey,provideLocalInfoESN,GPRSCallControl,NetSearchMode,provideLocalInfoIMEISV,BatteryInfo,provideLocalInfoMEID)>
  <!ELEMENT maximumNumberSoftKeys (#PCDATA)>
  <!ELEMENT numberDisplayCharactersDown (#PCDATA)>
  <!ELEMENT numberChannels (#PCDATA)>
  <!ELEMENT bipFilterRetransData (#PCDATA)>
  <!ELEMENT bipLogReceptionData (#PCDATA)>
  <!ELEMENT bipOcpUrl (#PCDATA)>
  <!ELEMENT bipLoadUrl (#PCDATA)>
  <!ELEMENT maxWaitForReceiveData (#PCDATA)>
  <!ELEMENT maxWaitForHttpResponse (#PCDATA)>
  <!ELEMENT numberDisplayCharactersAccross (#PCDATA)>
  <!ELEMENT menuWidthReduction (#PCDATA)>
  <!ELEMENT selectItemSoftKey (#PCDATA)>
  <!ELEMENT setupMenuSoftKey (#PCDATA)>
  <!ELEMENT eventDownloadBrowserTermination (#PCDATA)>
  <!ELEMENT eventDownloadDataAvailable (#PCDATA)>
  <!ELEMENT eventDownloadChannelStatus (#PCDATA)>
  <!ELEMENT eventAccessTechnoChange (#PCDATA)>
  <!ELEMENT eventDisplayParamsChanged (#PCDATA)>
  <!ELEMENT eventLocalConnection (#PCDATA)>
  <!ELEMENT getReaderStatusCardReaderId (#PCDATA)>
  <!ELEMENT launchBrowser (#PCDATA)>
  <!ELEMENT provideLocalInfoAccessTechno (#PCDATA)>
  <!ELEMENT provideLocalInfoIMEISV (#PCDATA)>
  <!ELEMENT provideLocalInfoMEID (#PCDATA)>
  <!ELEMENT getChannelStatus (#PCDATA)>
  <!ELEMENT serviceSearch (#PCDATA)>
  <!ELEMENT getServiceInfo (#PCDATA)>
  <!ELEMENT declareService (#PCDATA)>
  <!ELEMENT sendData (#PCDATA)>
  <!ELEMENT receiveData (#PCDATA)>
  <!ELEMENT closeChannel (#PCDATA)>
  <!ELEMENT openChannel (#PCDATA)>
  <!ELEMENT GPRS (#PCDATA)>
  <!ELEMENT CSD (#PCDATA)>
  <!ELEMENT bluetooth (#PCDATA)>
  <!ELEMENT IrDA (#PCDATA)>
  <!ELEMENT RS232 (#PCDATA)>
  <!ELEMENT screenSizing (#PCDATA)>
  <!ELEMENT variableSizeFonts (#PCDATA)>
  <!ELEMENT textScrolling (#PCDATA)>
  <!ELEMENT textAttributes (#PCDATA)>
  <!ELEMENT textWrapping (#PCDATA)>
  <!ELEMENT displayResizable (#PCDATA)>
  <!ELEMENT UDP (#PCDATA)>
  <!ELEMENT TCPClient (#PCDATA)>
  <!ELEMENT TCPServer (#PCDATA)>
  <!ELEMENT refresh (#PCDATA)>
  <!ELEMENT moreTime (#PCDATA)>
  <!ELEMENT pollInterval (#PCDATA)>
  <!ELEMENT pollingOff (#PCDATA)>
  <!ELEMENT setupCall (#PCDATA)>
  <!ELEMENT sendSs (#PCDATA)>
  <!ELEMENT sendShortMsg (#PCDATA)>
  <!ELEMENT sendUssd (#PCDATA)>
  <!ELEMENT playTone (#PCDATA)>
  <!ELEMENT displayText (#PCDATA)>
  <!ELEMENT getInkey (#PCDATA)>
  <!ELEMENT getInput (#PCDATA)>
  <!ELEMENT selectItem (#PCDATA)>
  <!ELEMENT setupMenu (#PCDATA)>
  <!ELEMENT performCardApdu (#PCDATA)>
  <!ELEMENT powerOnCard (#PCDATA)>
  <!ELEMENT powerOffCard (#PCDATA)>
  <!ELEMENT getReaderStatus (#PCDATA)>
  <!ELEMENT localInfoMcc (#PCDATA)>
  <!ELEMENT localInfoNmr (#PCDATA)>
  <!ELEMENT localInfoLanguage (#PCDATA)>
  <!ELEMENT localInfoTiming (#PCDATA)>
  <!ELEMENT timerManagementStart (#PCDATA)>
  <!ELEMENT timerManagementCurrentValue (#PCDATA)>
  <!ELEMENT localInfoDate (#PCDATA)>
  <!ELEMENT setUpIdleMode (#PCDATA)>
  <!ELEMENT runAtCommand (#PCDATA)>
  <!ELEMENT languageNotification (#PCDATA)>
  <!ELEMENT sendDtmfCommand (#PCDATA)>
  <!ELEMENT timerExpirationStk (#PCDATA)>
  <!ELEMENT eventDownloadCallConnectedStk (#PCDATA)>
  <!ELEMENT eventDownloadCallDisconnectedStk (#PCDATA)>
  <!ELEMENT eventDownloadLocationStatusStk (#PCDATA)>
  <!ELEMENT setUpEventListStk (#PCDATA)>
  <!ELEMENT eventDownloadMTCallStk (#PCDATA)>
  <!ELEMENT userActivityStk (#PCDATA)>
  <!ELEMENT eventDownloadIdleScreenStk (#PCDATA)>
  <!ELEMENT eventDownloadCardReaderStatusStk (#PCDATA)>
  <!ELEMENT eventDownloadLanguageSelectionStk (#PCDATA)>
  <!ELEMENT variableTimeoutDisplayText (#PCDATA)>
  <!ELEMENT helpSupportedGetInkey (#PCDATA)>
  <!ELEMENT USB (#PCDATA)>
  <!ELEMENT variableTimeoutGetInkey (#PCDATA)>
  <!ELEMENT provideLocalInfoESN (#PCDATA)>
  <!ELEMENT GPRSCallControl (#PCDATA)>
  <!ELEMENT NetSearchMode (#PCDATA)>
  <!ELEMENT BatteryInfo (#PCDATA)>
  <!ELEMENT downloadProfile (profileDonwload,smsPpData,cellBroadCast,menuSelection)>
  <!ELEMENT profileDonwload (#PCDATA)>
  <!ELEMENT smsPpData (#PCDATA)>
  <!ELEMENT cellBroadCast (#PCDATA)>
  <!ELEMENT menuSelection (#PCDATA)>
  <!ELEMENT others (customCapabilities,customCapabilitiesEnabled,callControl,commandResult,ucs2Display,moSm,ucs2Entry)>
  <!ELEMENT customCapabilities (#PCDATA)>
  <!ELEMENT customCapabilitiesEnabled (#PCDATA)>
  <!ELEMENT callControl (#PCDATA)>
  <!ELEMENT commandResult (#PCDATA)>
  <!ELEMENT ucs2Display (#PCDATA)>
  <!ELEMENT moSm (#PCDATA)>
  <!ELEMENT ucs2Entry (#PCDATA)>
  <!ELEMENT icons (iconSupported,iconColorSupported,iconTextMaxWidth,iconTextMaxHeight,iconOnlyMaxWidth,iconOnlyMaxHeight,iconItemMaxWidth,iconItemMaxHeight,iconPixelCorrespondenceWidht,iconPixelCorrespondenceHeight)>
  <!ELEMENT iconSupported (#PCDATA)>
  <!ELEMENT iconColorSupported (#PCDATA)>
  <!ELEMENT iconTextMaxWidth (#PCDATA)>
  <!ELEMENT iconTextMaxHeight (#PCDATA)>
  <!ELEMENT iconOnlyMaxWidth (#PCDATA)>
  <!ELEMENT iconOnlyMaxHeight (#PCDATA)>
  <!ELEMENT iconItemMaxWidth (#PCDATA)>
  <!ELEMENT iconItemMaxHeight (#PCDATA)>
  <!ELEMENT iconPixelCorrespondenceWidht (#PCDATA)>
  <!ELEMENT iconPixelCorrespondenceHeight (#PCDATA)>
  <!ELEMENT events (eventDownloadBrowserTerminationCause,eventDownloadCallConnected,eventDownloadCallDisconnected,eventDownloadLocationStatus,eventDownloadMTCall,userActivity,evenDownloadIdleScreen,eventDownloadCardReaderStatus,eventDownloadLanguageSelection,envelopeCallControl,eventDownloadDataAvailable,eventDownloadChannelStatus)>
  <!ELEMENT eventDownloadBrowserTerminationCause (#PCDATA)>
  <!ELEMENT timerExpiration (#PCDATA)>
  <!ELEMENT eventDownloadCallConnected (#PCDATA)>
  <!ELEMENT eventDownloadCallDisconnected (#PCDATA)>
  <!ELEMENT eventDownloadLocationStatus (#PCDATA)>
  <!ELEMENT eventDownloadMTCall (#PCDATA)>
  <!ELEMENT userActivity (#PCDATA)>
  <!ELEMENT evenDownloadIdleScreen (#PCDATA)>
  <!ELEMENT eventDownloadCardReaderStatus (#PCDATA)>
  <!ELEMENT eventDownloadLanguageSelection (#PCDATA)>
  <!ELEMENT envelopeCallControl (#PCDATA)>
  <!ELEMENT spy (onTheFlyAnalysis,logTraceFile,logTraceFileName,compareSimResponse,stopOnDiffResponse,recordFileName,spyEnabled)>
  <!ELEMENT onTheFlyAnalysis (#PCDATA)>
  <!ELEMENT logTraceFile (#PCDATA)>
  <!ELEMENT logTraceFileName (#PCDATA)>
  <!ELEMENT compareSimResponse (#PCDATA)>
  <!ELEMENT stopOnDiffResponse (#PCDATA)>
  <!ELEMENT recordFileName (#PCDATA)>
  <!ELEMENT spyEnabled (#PCDATA)>
  <!ELEMENT boot (useAIDValue,AIDDefaultValue)>
  <!ELEMENT useAIDValue (#PCDATA)>
  <!ELEMENT AIDDefaultValue (#PCDATA)>
  <!ELEMENT bip (bipdelaytimer,bufferSize,destinationAddress,localPort,transportProtocol)>
  <!ATTLIST bip channel CDATA "1">
  <!ELEMENT bipdelaytimer (#PCDATA)>
  <!ELEMENT bufferSize (#PCDATA)>
  <!ELEMENT destinationAddress (useDestinationAddressValue,destinationAddressDefaultValue)>
  <!ELEMENT useDestinationAddressValue (#PCDATA)>
  <!ELEMENT destinationAddressDefaultValue (#PCDATA)>
  <!ELEMENT localPort (#PCDATA)>
  <!ELEMENT transportProtocol (useTransportProtocolValue,transportProtocolValueDefaultValue)>
  <!ELEMENT useTransportProtocolValue (#PCDATA)>
  <!ELEMENT transportProtocolValueDefaultValue (#PCDATA)>]>

<Options>
  <mobileOptions>
    <optionsItems>
      <terminalInterface>
        <selectedTerminalInterface>gemalto</selectedTerminalInterface>
        <othersTerminaleInterface>gemalto</othersTerminaleInterface>
      </terminalInterface>
      <delayDisplay>3000</delayDisplay>
      <delayUserResponse>500</delayUserResponse>
      <defaultTimeIntervalStatusCommand>30000</defaultTimeIntervalStatusCommand>
      <statusCommandAvailable>false</statusCommandAvailable>
      <toneDuration>100</toneDuration>
      <toneType>
        <mute>false</mute>
        <pc>true</pc>
        <set1>false</set1>
        <set2>false</set2>
      </toneType>
      <sizeScreenPolicy>3</sizeScreenPolicy>
      <styleScreenPolicy>SimSun</styleScreenPolicy>
      <colorScreenPolicy>000000</colorScreenPolicy>
      <cardTimeout>20000</cardTimeout>
      <batteryInfo>4</batteryInfo>
      <netsearchmode>0</netsearchmode>
      <IMEI>112233445566770</IMEI>
	  <IMEISV>1122334455667788</IMEISV>
	  <MEID>961234565566770</MEID>
      <cardReset>true</cardReset>
    </optionsItems>
  </mobileOptions>
  <terminalProfile>
    <proactiveCommands>
      <maximumNumberSoftKeys>0</maximumNumberSoftKeys>
      <numberDisplayCharactersDown>6</numberDisplayCharactersDown>
      <numberChannels>7</numberChannels>
      <bipFilterRetransData>false</bipFilterRetransData>
      <bipLogReceptionData>false</bipLogReceptionData>
      <bipOcpUrl>http://127.0.0.1:3516/</bipOcpUrl>
      <bipLoadUrl>http://127.0.0.1:3516/</bipLoadUrl>
      <maxWaitForReceiveData>60000</maxWaitForReceiveData>
      <maxWaitForHttpResponse>60000</maxWaitForHttpResponse>
      <numberDisplayCharactersAccross>24</numberDisplayCharactersAccross>
      <menuWidthReduction>0</menuWidthReduction>
      <eventDownloadBrowserTermination>true</eventDownloadBrowserTermination>
      <eventDownloadDataAvailable>true</eventDownloadDataAvailable>
      <eventDownloadChannelStatus>true</eventDownloadChannelStatus>
      <eventAccessTechnoChange>false</eventAccessTechnoChange>
      <eventDisplayParamsChanged>false</eventDisplayParamsChanged>
      <eventLocalConnection>false</eventLocalConnection>
      <getReaderStatusCardReaderId>false</getReaderStatusCardReaderId>
      <launchBrowser>true</launchBrowser>
      <provideLocalInfoAccessTechno>false</provideLocalInfoAccessTechno>
      <getChannelStatus>true</getChannelStatus>
      <serviceSearch>false</serviceSearch>
      <getServiceInfo>false</getServiceInfo>
      <declareService>false</declareService>
      <sendData>true</sendData>
      <receiveData>true</receiveData>
      <closeChannel>true</closeChannel>
      <openChannel>true</openChannel>
      <GPRS>true</GPRS>
      <CSD>true</CSD>
      <bluetooth>true</bluetooth>
      <IrDA>true</IrDA>
      <RS232>true</RS232>
      <screenSizing>true</screenSizing>
      <variableSizeFonts>true</variableSizeFonts>
      <textScrolling>true</textScrolling>
      <textAttributes>false</textAttributes>
      <textWrapping>false</textWrapping>
      <displayResizable>false</displayResizable>
      <UDP>true</UDP>
      <TCPClient>true</TCPClient>
      <TCPServer>true</TCPServer>
      <selectItemSoftKey>false</selectItemSoftKey>
      <setupMenuSoftKey>false</setupMenuSoftKey>
      <refresh>true</refresh>
      <moreTime>true</moreTime>
      <pollInterval>true</pollInterval>
      <pollingOff>true</pollingOff>
      <setupCall>true</setupCall>
      <sendSs>true</sendSs>
      <sendShortMsg>true</sendShortMsg>
      <sendUssd>true</sendUssd>
      <playTone>true</playTone>
      <displayText>true</displayText>
      <getInkey>true</getInkey>
      <getInput>true</getInput>
      <selectItem>true</selectItem>
      <setupMenu>true</setupMenu>
      <performCardApdu>true</performCardApdu>
      <powerOnCard>true</powerOnCard>
      <powerOffCard>true</powerOffCard>
      <getReaderStatus>true</getReaderStatus>
      <localInfoMcc>true</localInfoMcc>
      <localInfoNmr>false</localInfoNmr>
      <localInfoLanguage>false</localInfoLanguage>
      <localInfoTiming>false</localInfoTiming>
      <timerManagementStart>true</timerManagementStart>
      <timerManagementCurrentValue>true</timerManagementCurrentValue>
      <localInfoDate>true</localInfoDate>
      <setUpIdleMode>false</setUpIdleMode>
      <runAtCommand>false</runAtCommand>
      <languageNotification>false</languageNotification>
      <sendDtmfCommand>false</sendDtmfCommand>
      <timerExpirationStk>true</timerExpirationStk>
      <eventDownloadCallConnectedStk>true</eventDownloadCallConnectedStk>
      <eventDownloadCallDisconnectedStk>true</eventDownloadCallDisconnectedStk>
      <eventDownloadLocationStatusStk>true</eventDownloadLocationStatusStk>
      <setUpEventListStk>true</setUpEventListStk>
      <eventDownloadMTCallStk>true</eventDownloadMTCallStk>
      <userActivityStk>false</userActivityStk>
      <eventDownloadIdleScreenStk>false</eventDownloadIdleScreenStk>
      <eventDownloadCardReaderStatusStk>false</eventDownloadCardReaderStatusStk>
      <eventDownloadLanguageSelectionStk>false</eventDownloadLanguageSelectionStk>
      <variableTimeoutDisplayText>false</variableTimeoutDisplayText>
      <helpSupportedGetInkey>false</helpSupportedGetInkey>
      <USB>false</USB>
      <variableTimeoutGetInkey>false</variableTimeoutGetInkey>
      <provideLocalInfoESN>false</provideLocalInfoESN>
      <GPRSCallControl>false</GPRSCallControl>
      <NetSearchMode>false</NetSearchMode>
      <provideLocalInfoIMEISV>true</provideLocalInfoIMEISV>
      <BatteryInfo>false</BatteryInfo>
	  <provideLocalInfoMEID>true</provideLocalInfoMEID>
    </proactiveCommands>
    <downloadProfile>
      <profileDonwload>true</profileDonwload>
      <smsPpData>true</smsPpData>
      <cellBroadCast>false</cellBroadCast>
      <menuSelection>true</menuSelection>
    </downloadProfile>
    <others>
      <customCapabilities>20 00 FB F7 FF 7F 1F 03 0F CB 41 1F 00 00 00 86 07 C4 00 00 00 02 20 00 00 00 00 00 00 00</customCapabilities>
      <customCapabilitiesEnabled>false</customCapabilitiesEnabled>
      <callControl>true</callControl>
      <commandResult>true</commandResult>
      <ucs2Display>true</ucs2Display>
      <moSm>false</moSm>
      <ucs2Entry>true</ucs2Entry>
    </others>
  </terminalProfile>
  <icons>
    <iconSupported>true</iconSupported>
    <iconColorSupported>true</iconColorSupported>
    <iconTextMaxWidth>17</iconTextMaxWidth>
    <iconTextMaxHeight>22</iconTextMaxHeight>
    <iconOnlyMaxWidth>96</iconOnlyMaxWidth>
    <iconOnlyMaxHeight>64</iconOnlyMaxHeight>
    <iconItemMaxWidth>6</iconItemMaxWidth>
    <iconItemMaxHeight>9</iconItemMaxHeight>
    <iconPixelCorrespondenceWidht>1</iconPixelCorrespondenceWidht>
    <iconPixelCorrespondenceHeight>1</iconPixelCorrespondenceHeight>
  </icons>
  <events>
    <eventDownloadBrowserTerminationCause>true</eventDownloadBrowserTerminationCause>
    <eventDownloadCallConnected>true</eventDownloadCallConnected>
    <eventDownloadCallDisconnected>true</eventDownloadCallDisconnected>
    <eventDownloadLocationStatus>true</eventDownloadLocationStatus>
    <eventDownloadMTCall>true</eventDownloadMTCall>
    <userActivity>false</userActivity>
    <evenDownloadIdleScreen>false</evenDownloadIdleScreen>
    <eventDownloadCardReaderStatus>false</eventDownloadCardReaderStatus>
    <eventDownloadLanguageSelection>false</eventDownloadLanguageSelection>
    <envelopeCallControl>true</envelopeCallControl>
    <eventDownloadDataAvailable>true</eventDownloadDataAvailable>
    <eventDownloadChannelStatus>true</eventDownloadChannelStatus>
  </events>
  <spy>
    <onTheFlyAnalysis>true</onTheFlyAnalysis>
    <logTraceFile>true</logTraceFile>
    <logTraceFileName>spy000.log</logTraceFileName>
    <compareSimResponse>true</compareSimResponse>
    <stopOnDiffResponse>true</stopOnDiffResponse>
    <recordFileName>spy000.spy</recordFileName>
    <spyEnabled>true</spyEnabled>
  </spy>
  <boot>
    <useAIDValue>false</useAIDValue>
    <AIDDefaultValue>A0 00 00 00 87 10 02 F3 10 FF FF 89 00 00 01 FF</AIDDefaultValue>
  </boot>
  <bip channel="1">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>3516</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="2">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10081</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="3">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10082</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="4">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10083</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="5">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10084</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="6">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10085</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="7">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10086</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
  <bip channel="8">
    <bipdelaytimer>1000</bipdelaytimer>
    <bufferSize>15000</bufferSize>
    <destinationAddress>
      <useDestinationAddressValue>false</useDestinationAddressValue>
      <destinationAddressDefaultValue>127.0.0.1:8080</destinationAddressDefaultValue>
    </destinationAddress>
    <localPort>10087</localPort>
    <transportProtocol>
      <useTransportProtocolValue>false</useTransportProtocolValue>
      <transportProtocolValueDefaultValue>TCPClient</transportProtocolValueDefaultValue>
    </transportProtocol>
  </bip>
</Options>